### ISSUE TITLE
Allow deletion of old, unused versions

### ISSUE THREAD

**Issue by thoean** [wparad/aws-architect.js#43]
Function and layer storage per region (across all functions) is at 75 GB. See [documentation](https://docs.aws.amazon.com/lambda/latest/dg/limits.html).

It's a soft-limit, and can be increased. However, storing all of your Lambda history forever might not be worth it, especially that many might have been pull requests.

So I have this code, and I wonder whether it's worthwile putting this into a generic function in aws-architect, or alternatively into the `make.js` of the template.

```javascript
commander
  .command('cleanup-lambda-code')
  .description('Cleans up old, unused Lambda code')
  .action(async () => {
    let dryRun = process.env.CI_COMMIT_REF_SLUG !== 'master';
    let lambda = new AWS.Lambda({ region: 'eu-west-1' });
    let nextToken = null;
    let functionName = packageMetadata.name;
    let keepFunctionsYoungerThanDays = 1;
    let functions = [];

    // get lambda versions
    do {
      let functionsBatch = await lambda.listVersionsByFunction({ FunctionName: functionName, Marker: nextToken }).promise();
      functions = functions.concat(functionsBatch.Versions);
      nextToken = functionsBatch.NextMarker;
    } while (nextToken);

    // get lambda aliases
    let aliases = [];
    do {
      let functionsBatch = await lambda.listAliases({ FunctionName: functionName, Marker: nextToken }).promise();
      aliases = aliases.concat(functionsBatch.Aliases);
      nextToken = functionsBatch.NextMarker;
    } while (nextToken);
    
    // log statistics
    let totalCodeSize = functions.map(f => f.CodeSize).reduce((prev, curr) => prev + curr, 0);
    console.log(`Total code size of all functions: ${totalCodeSize / 1000 / 1000} MB`);

    // remove protected versions to be eligible to be deleted based on alias mapping
    let protectedAliases = new Set(['production']);
    let protectedVersions = aliases.filter(a => protectedAliases.has(a.Name)).map(a => a.FunctionVersion);
    protectedVersions = protectedVersions.concat('$LATEST'); // always remove special $LATEST version
    let protectedVersionsLookup = new Set(protectedVersions);
    functions = functions.filter(f => !protectedVersionsLookup.has(f.Version));

    // filter out newer versions to only cleanup old versions
    let cutoff = new Date();
    cutoff.setDate(new Date().getDate() - keepFunctionsYoungerThanDays);
    functions = functions.filter(f => f.LastModified < cutoff.toISOString());

    // log statistics of versions that will be deleted
    let versions = functions.map(f => f.Version);
    let codeSize = functions.map(f => f.CodeSize).reduce((prev, curr) => prev + curr, 0);
    console.log(`Code size to be deleted: ${codeSize / 1000 / 1000} MB`);
    console.log(`Versions to be deleted: ${versions.length} versions - specific list: ${JSON.stringify(versions)}`);

    // delete aliases and functions
    for (let i = 0; i < functions.length; i++) {
      let f = functions[i];
      let aliasesForVersion = aliases.filter(a => a.FunctionVersion === f.Version);

      // aliases must be deleted before deleting the underlying version
      for (let j = 0; j < aliasesForVersion.length; j++) {
        let a = aliasesForVersion[j];
        console.log(`${dryRun ? '[DRY RUN only][DELETING]' : '[DELETING]'}: Alias ${a.Name} for function ${f.FunctionName} v${f.Version}`);
        if (!dryRun) {
          await lambda.deleteAlias({ FunctionName: functionName, Name: a.Name }).promise();
        }
      }

      // delete the function version
      console.log(`${dryRun ? '[DRY RUN only][DELETING]' : '[DELETING]'}: Function ${f.FunctionName}.${f.Version} from ${f.LastModified} with size ${f.CodeSize / 1000 / 1000} MB.`);
      if (!dryRun) {
        await lambda.deleteFunction({ FunctionName: functionName, Qualifier: f.Version }).promise();
      }
    }
  });
```

I was also thinking of having a delete command when the MR gets deleted, but you don't know which versions were used for this MR. So the alternative would be to have this generic function available, and have the client specify the number of days going back. However, for functions that haven't been deployed for a long time, it'd also delete the previous production function and a rollback would be way harder (probably an OK trade-off for many situations).

Thoughts of re-using this type of code somewhere in here?

**Comment by wparad** [comment]
> I was also thinking of having a delete command when the MR gets deleted, but you don't know which versions were used for this MR

I think that would be the preferred approach, and we should know which version because it still has an alias. We delete the api gateway stage, which has the alias stored in it, but either way the "naming convention" is created by this library so we should be able to figure out what to delete.

Other than the original caveat, is there a reason not to implement it into the `make.js` delete function to remove only `this` MR alias + version?

**Comment by thoean** [comment]
If you push 5 versions on a MR, then only the last version will have the MR's alias. So you won't delete 4 of them. I mean, it might be a reasonable trade-off, but it's not eliminating much of it. (In our case, we have many "Work-in-progress" previews of MRs, so I expect it'd be way less than 50% for us. I understand different teams might have better results.)

So I only could come up with something time-based, and let it up to the client to define the time range for the cleanup. (An alternative is to introduce additional aliases, like `pull-request-some-feature-v1` in increment the `-v1` with every push. Then we could leverage naming patterns to really delete them. (And it'd keep all production versions around forever, which might be OK, depending on team and type of Lambda function.)

Overall, I think it's a list of trade-offs we need to decide whether it's just another helper method in `make.js` or something a bit more integrated.

**Comment by wparad** [comment]
If we deleted the "current version" of a alias every time we went to assign it to a new one would that work? (obviously needing an extra parameter to exclude `production`)

**Comment by wparad** [comment]
Okay, I think we should add your suggested to code to the make.js, but I think we should make two adjustments:
* Move the deleteAlias code to the `awsArchitect.removeStagePromise()` method
* Ignore all function versions with any alias (would that avoid having to make to additional calls to lambda to get all the aliases?)

**Comment by thoean** [comment]
I like the option to delete the version once we repoint it (except for an exclusion list like the "production" alias to keep those versions "forever").

Yes, getting the aliases is a different call than getting the versions.

I can have a look at this in a few days - having this code around gets us short-term over some limitations with a manual cleanup, but obviously having a long-term solution available is desired.

**Comment by wparad** [comment]
This functionality exists now by default in the package as well as helper to do more refined stuff. Closing.
